### ISSUE TITLE
assignment operator

### ISSUE THREAD

**Issue by lbrichards** [Sane21/meizen#3]
Do you plan to support the assignment operator `←` ?

**Comment by Sane21** [comment]
I'm wondering if I should support assignment operator `←`  and other operators shown in 「共通テスト手順記述標準言語 (DNCL) の説明」(2022/01).
The Common Test "Information" probably use new DNCL shown in 「試作問題「情報」の概要」.

I'm worried about the difference between 2022 ver. and newer version make students confused, and not supporting old DNCL now.

Do you think operator `←` supporting is necessary?

**Comment by Sane21** [comment]
Implemented operators and syntaxes are shown in this file.
They are basically referring to the newer DNCL specifications.

https://github.com/Sane21/meizen/tree/main/meizen/dncl/symbol.py

**Comment by Sane21** [comment]
I've supported operator `←` just now.

**Comment by lbrichards** [comment]
Thank you for your quick responses!
I share your concern about multiple versions.  So far I was assuming this [https://klab.eplang.jp/honda/dncl/](https://klab.eplang.jp/honda/dncl/ ) to be compliant with the latest "official" version, but since ← has been removed, I guess not.  (This is a very nice tool, btw, which a lot of 受験生 will probably see and use, which makes it a bit dangerous too.)
Do you know of a complete DNCL language specification covering the latest official version?  My aim is to provide my python students with accurate tools to help them understand (the official version of) DNCL.

**Comment by lbrichards** [comment]
Another problem with https://klab.eplang.jp/honda/dncl/ is that it uses 1-based indexing, whereas the latest version uses 0-based indexing.
I think it would be beneficial for everyone to have an online resource containing executable examples from the latest DNCL, along with the capability to display ascii DNCL and covert to/from python.

**Comment by lbrichards** [comment]
This seems like a good resource:  https://note.com/toppakou/n/n08dfe37acc78

**Comment by Sane21** [comment]
Thank you for your reply and opinions.
My aim is to help all students who learn Programming via DNCL.

I think that the latest DNCL official specification is shown in [共通テスト手順記述標準言語 (DNCL) の説明](https://www.dnc.ac.jp/albums/abm.php?d=67&f=abm00000819.pdf&n=R4_%E5%85%B1%E9%80%9A%E3%83%86%E3%82%B9%E3%83%88%E6%89%8B%E9%A0%86%E8%A8%98%E8%BF%B0%E6%A8%99%E6%BA%96%E8%A8%80%E8%AA%9E%EF%BC%88DNCL%EF%BC%89%E3%81%AE%E8%AA%AC%E6%98%8E.pdf), and DNCL is defined for subject of the Common Test  for University Adminissions 「情報関係基礎(meaning : Information Related Fundamentals)」.
However, the Common Test in subsequent years will replace 「情報関係基礎」to「情報(meaning: Information)」, and use the New Language similar to DNCL, but not DNCL.

For convenience, I call the New Language "DNCL2". 
The latest DNCL2 official specification is shown in [試作問題「情報」の概要(meaning: the Abstract of sample exam "Information")](https://www.dnc.ac.jp/albums/abm.php?d=511&f=abm00003141.pdf&n=6-1_%E6%A6%82%E8%A6%81%E3%80%8C%E6%83%85%E5%A0%B1%E3%80%8D.pdf) page18.
My python package "meizen" is referred to this document.


These are good service that can run DNCL and newer DNCL2, probably referring to the same document, too.
Tsuchinoko : https://t-daimon.jp/tsuchinoko/ide/
PyPEN : https://watayan.net/prog/PyPEN/

**Comment by lbrichards** [comment]
Thank you for your help and advice!  I have a better understanding now.  Those are nice resources, too.
